### ISSUE TITLE
Add CoreEntity methods to the objects that extend it

### ISSUE THREAD

**Issue by gchtr** [timber/teak#4]
By moving the `meta()` methods to `Timber\CoreEntity` in https://github.com/timber/timber/pull/2397, the `meta()` methods do not appear in the documentation anymore.

**Related**:

- https://github.com/timber/timber/issues/2982

**Todo**:

- [ ]  Make `@inheritDoc` work ([[link](https://github.com/timber/timber/pull/2397#discussion_r628728654)](https://github.com/timber/timber/pull/2397#discussion_r628728654)).
- [ ]  Use non-generic documentation for the various object types. Maybe work with a DocBlock-variable that can be replaced somehow ([[link](https://github.com/timber/timber/pull/2397#discussion_r628730474)](https://github.com/timber/timber/pull/2397#discussion_r628730474)).
- [ ]  Add `@api` tag to `CoreEntity` ([[link](https://github.com/timber/timber/pull/2397#discussion_r628732794)](https://github.com/timber/timber/pull/2397#discussion_r628732794)).

**Comment by gchtr** [comment]
I think I’ll close this because now public methods of parent classes are inherited automatically.
